/*******************************************************************************
* File name： OrderUpdaetEvent.h
* Description: HuobiSwap api OrderUpdateEvent header files.
* Author: QiaoXiaofeng(andyjoe318@gmail.com)
* Version: 0.0.1
* Date： 2020-05-26
* History: 
*
*******************************************************************************/

#ifndef ORDERUPDATEEVENT_H
#define ORDERUPDATEEVENT_H

#include <string>
#include "Order.h"

namespace HuobiSwap {

    /**
     * The order update received by subscription of order update.
     */
    struct OrderUpdateEvent {
        /**
         * The contract code.
         */
        std::string symbol;

        /**
         * The UNIX formatted timestamp generated by server in UTC.
         */
        long timestamp;

        /**
         * The order detail.
         */
        Order data;

        /**
         * The client order id defined  by user .
         */
        std::string client_order_id;

        /**
         * The unfilled volume.
         */
        Decimal unfilled_volume;

    };
}

#endif /* ORDERUPDATEEVENT_H */